version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "auth-sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1t5zw1r83511s"
s3_prefix = "auth-sam-app"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
